language: php

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0
 - hhvm

before_script:
 - composer install --no-dev --quiet

script:
 - mkdir -p build/logs
 - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v