language: php

php:
 - '5.5'
 - '5.6'
 - '7.0'
 - hhvm

before_script:
 - curl -s http://getcomposer.org/installer | php
 - php composer.phar install --dev --no-interaction

script:
 - mkdir -p build/logs
 - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
