language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

sudo: false

before_install:
  - travis_retry composer self-update && composer --version

install:
  - travis_retry composer install

cache:
  directories:
    - $HOME/.composer/cache
    - vendor