language: php
php:
  - "5.6"
  - "7.0"
before_script:
  - if [ "$deps" == "low" ]; then composer update --prefer-source --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-source; fi